# Main configuration file for multiServer.
# Please read README.md on github before reporting a bug.
#
# To edit server list go to *\.multiServer\servers.yml
# To run servers start 'multiServer-app.exe'
# 
# Created by: Kyoshuske
# Uploaded on: github.com/kyoshuske
# Version: 1.2.7
# 
# If you need help or if you want to report a bug,
# join our discord server below and create a forum post.
# 
# GitHub: https://github.com/kyoshuske/multiServer
# Discord: **currently closed**
#
settings:
  global:
    global-filename:
      enable: false
      filename: global-servername.jar
    global-color:
      enable: false
      color: 2
    global-javafile:
      enable: true
      filename: java
  app:
    resolution:
      width: 820
      height: 1300
    port: 42434
    mode: webbrowser # if you don't know what it does, don't change it (webbrowser/subprocess)
