# Main configuration file for multiServer.
# Please read README.md on github before reporting a bug.
#
# To edit server list go to *\.multiServer\servers.yml
# To run app start 'multiServer-START_THIS.bat'
# 
# Created by: Kyoshuske
# Uploaded on: github.com/kyoshuske/multiServer
# Version: 1.2.9 (if you are updating multiServer please backup all of your configuration files) 
# 
# If you need help or if you want to report a bug,
# add me on discord and dm me.
# 
# GitHub: @kyoshuske
# Discord: @kyoshuske
#
settings:
  global:
    global-filename:
      enable: false
      filename: global-servername.jar
    global-javafile:
      enable: true
      filename: java
  app:
    resolution:
      width: 820
      height: 1300
    port: 42434
    mode: webbrowser # if you don't know what it does, don't change it (webbrowser/subprocess/experimental)
    console-refresh-rate: 0.2
