# Main configuration file for multiServer.
#
# To edit server list go to .\.multiServer\servers.yml
# To run app start 'launcher.exe'
# 
# Created by: Kyoshuske
# Uploaded on: github.com/kyoshuske/multiServer
# Version: 1.3.0 (if you are updating multiServer please backup all of your configuration files)
# 
# If you need help or if you want to report a bug,
# add me on discord and dm me.
# 
# GitHub: @kyoshuske
# Discord: @kyoshuske
#
settings:
  global:
    java:
      enable: true
      path: java
    plugins:
      enable: false
      directory: c:\example-plugins
      whitelist:
        invert: false 
        servers: 
          - example-server2
    # By changing the setting below to TRUE or any other value listed below you are indicating your agreement to mojang's EULA (https://account.mojang.com/documents/minecraft_eula).
    # [y, Y, yes, Yes, YES, true, True, TRUE, on, On, ON]
    eula: false
  app:
    resolution:
      width: 820
      height: 1300
    port: 42434
    reload-server-config: false # when true: reloads server's config everytime when start button is clicked [true/false, default: false]
    mode: system # changes how servers are being started [system/subprocess/webbrowser/experimental, default: system]
    experimental-mode:
      console-refresh-rate: 0.00001
      max-console-output: 1800
