#
# example 'config.yml' file 
#

 settings:
   global:
     global-filename:
       enable: false
       filename: global-servername.jar
     global-color:
       enable: true
       color: 7
     global-javafile:
       enable: true
       filename: java
  app:
    resolution:
      width: 820
      height: 1300
    port: 42434
